### ISSUE TITLE
Error recover a version

### ISSUE THREAD

**Issue by cfoellmann** [ATM-Consulting/dolibarr_module_propalehistory#34]
On the current dev 14.x version of Dolibarr I get an error when trying to recover a saved version of a propale.

```
Fatal error: 
Uncaught Error: Call to undefined method Propal::setDateLivraison() in /home/runcloud/webapps/erp-staging/htdocs/custom/propalehistory/class/propaleHist.class.php:179 
Stack trace: 
#0 /home/runcloud/webapps/erp-staging/htdocs/custom/propalehistory/class/actions_propalehistory.class.php(223): TPropaleHist::restaurerPropale() 
#1 /home/runcloud/webapps/erp-staging/htdocs/core/class/hookmanager.class.php(275): ActionsPropalehistory->doActions() 
#2 /home/runcloud/webapps/erp-staging/htdocs/comm/propal/card.php(144): HookManager->executeHooks() 
#3 {main} thrown in /home/runcloud/webapps/erp-staging/htdocs/custom/propalehistory/class/propaleHist.class.php on line 179
```

**Comment by atm-john** [comment]
Thank for your feedback !

**Comment by cfoellmann** [comment]
I am still getting errors:


the real_escape_string() errors is about 20-30 times

```
Warning: mysqli::real_escape_string() expects parameter 1 to be string, array given in /home/runcloud/webapps/erp-staging/htdocs/core/db/mysqli.class.php on line 430

Warning: Cannot modify header information - headers already sent by (output started at /home/runcloud/webapps/erp-staging/htdocs/core/db/mysqli.class.php:430) in /home/runcloud/webapps/erp-staging/htdocs/custom/propalehistory/class/propaleHist.class.php on line 192

Warning: Cannot modify header information - headers already sent by (output started at /home/runcloud/webapps/erp-staging/htdocs/core/db/mysqli.class.php:430) in /home/runcloud/webapps/erp-staging/htdocs/main.inc.php on line 1302

Warning: Cannot modify header information - headers already sent by (output started at /home/runcloud/webapps/erp-staging/htdocs/core/db/mysqli.class.php:430) in /home/runcloud/webapps/erp-staging/htdocs/main.inc.php on line 1308

Warning: Cannot modify header information - headers already sent by (output started at /home/runcloud/webapps/erp-staging/htdocs/core/db/mysqli.class.php:430) in /home/runcloud/webapps/erp-staging/htdocs/main.inc.php on line 1310
```
